import type { Program } from "../types";
import { WYKAZ_AKT } from "./acts";

export const PROGRAM_TYPE = {
  PROGRAMOWY: "programowy",
  NIEPROGRAMOWY: "nieprogramowy",
} as const;

export const programs: Program[] = [
  {
    id: "1",
    code: WYKAZ_AKT["966"].subCategories?.["1"].code || null,
    name: "Trzymaj formę",
    programType: PROGRAM_TYPE.PROGRAMOWY,
    description: "",
  },
  {
    id: "2",
    code: WYKAZ_AKT["966"].subCategories?.["2"].code || null,
    name: "HIV/AIDS",
    programType: PROGRAM_TYPE.PROGRAMOWY,
    description: "",
  },
  {
    id: "3",
    code: WYKAZ_AKT["966"].subCategories?.["2"].code || null,
    name: "Ars - czyli jak dbać o miłość",
    programType: PROGRAM_TYPE.PROGRAMOWY,
    description: "",
  },
  {
    id: "4",
    code: WYKAZ_AKT["966"].subCategories?.["2"].code || null,
    name: "Światowy Dzień AIDS",
    programType: PROGRAM_TYPE.PROGRAMOWY,
    description: "",
  },
  {
    id: "5",
    code: WYKAZ_AKT["966"].subCategories?.["3"].code || null,
    name: "Zdrowe zęby mamy, marchewkę zajadamy",
    programType: PROGRAM_TYPE.PROGRAMOWY,
    description: "",
  },
  {
    id: "6",
    code: WYKAZ_AKT["966"].subCategories?.["4"].code || null,
    name: "Higiena naszą tarczą ochronną",
    programType: PROGRAM_TYPE.PROGRAMOWY,
    description: "",
  },
  {
    id: "7",
    code: WYKAZ_AKT["966"].subCategories?.["5"].code || null,
    name: "Porozmawiajmy o zdrowiu i nowych zagrożeniach",
    programType: PROGRAM_TYPE.PROGRAMOWY,
    description: "",
  },
  {
    id: "8",
    code: WYKAZ_AKT["966"].subCategories?.["6"].code || null,
    name: "Profilaktyka używania napojów energetycznych",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "9",
    code: WYKAZ_AKT["966"].subCategories?.["6"].code || null,
    name: "Profilaktyka palenia tytoniu",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "10",
    code: WYKAZ_AKT["966"].subCategories?.["6"].code || null,
    name: "Światowy Dzień Rzucania Palenia",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "11",
    code: WYKAZ_AKT["966"].subCategories?.["6"].code || null,
    name: "Nowe narkotyki",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "12",
    code: WYKAZ_AKT["966"].subCategories?.["7"].code || null,
    name: "Promocja zdrowego stylu życia - inne",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "13",
    code: WYKAZ_AKT["966"].subCategories?.["7"].code || null,
    name: "Promocja zdrowego stylu życia",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "14",
    code: WYKAZ_AKT["966"].subCategories?.["7"].code || null,
    name: "Skąd się biorą ekologiczne produkty",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "15",
    code: WYKAZ_AKT["966"].subCategories?.["7"].code || null,
    name: "Profilaktyka cukrzycy",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "16",
    code: WYKAZ_AKT["966"].subCategories?.["7"].code || null,
    name: "Kampania EFSA",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "17",
    code: WYKAZ_AKT["966"].subCategories?.["7"].code || null,
    name: "Bieg po zdrowie",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "18",
    code: WYKAZ_AKT["966"].subCategories?.["8"].code || null,
    name: "Podstępne WZW",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "19",
    code: WYKAZ_AKT["966"].subCategories?.["8"].code || null,
    name: "Profilaktyka chorób odkleszczowych",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "20",
    code: WYKAZ_AKT["966"].subCategories?.["8"].code || null,
    name: "Profilaktyka grypy",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "21",
    code: WYKAZ_AKT["966"].subCategories?.["9"].code || null,
    name: "Znamię, znam je",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "22",
    code: WYKAZ_AKT["966"].subCategories?.["9"].code || null,
    name: "Profilaktyka nowotworowa - Profilaktyka raka piersi",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "23",
    code: WYKAZ_AKT["966"].subCategories?.["9"].code || null,
    name: "Profilaktyka nowotworowa",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "24",
    code: WYKAZ_AKT["966"].subCategories?.["9"].code || null,
    name: "Profilaktyka nowotworowa - Profilaktyka raka jąder",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "25",
    code: WYKAZ_AKT["966"].subCategories?.["10"].code || null,
    name: "Profilaktyka bezpiecznego grzybobrania i profilaktyka zatruć grzybami",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "26",
    code: WYKAZ_AKT["966"].subCategories?.["11"].code || null,
    name: "Promocja szczepień ochronnych",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "27",
    code: WYKAZ_AKT["966"].subCategories?.["12"].code || null,
    name: "Światowy Dzień Zdrowia",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "28",
    code: WYKAZ_AKT["966"].subCategories?.["14"].code || null,
    name: "Bezpieczne ferie",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "29",
    code: WYKAZ_AKT["966"].subCategories?.["14"].code || null,
    name: "Bezpieczne Wakacje",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "30",
    code: WYKAZ_AKT["966"].subCategories?.["16"].code || null,
    name: "Promocja zdrowia psychicznego",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "31",
    code: WYKAZ_AKT["966"].subCategories?.["17"].code || null,
    name: "Wpływ czynników środowiskowych na zdrowie",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "32",
    code: WYKAZ_AKT["966"].subCategories?.["17"].code || null,
    name: "Czyste powietrze wokół nas",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "33",
    code: WYKAZ_AKT["966"].subCategories?.["17"].code || null,
    name: "Światowy Dzień Wody",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "34",
    code: WYKAZ_AKT["966"].subCategories?.["18"].code || null,
    name: "Moja szkoła, zdrowa szkoła",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "35",
    code: WYKAZ_AKT["966"].subCategories?.["18"].code || null,
    name: "Profilaktyka wad postawy",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
  {
    id: "36",
    code: WYKAZ_AKT["966"].subCategories?.["19"].code || null,
    name: "Power Ukraina",
    programType: PROGRAM_TYPE.NIEPROGRAMOWY,
    description: "",
  },
] as const;
