import type { School } from "../types";
import { schoolTypes } from ".";

export const schools: Omit<School, "id" | "createdAt" | "updatedAt">[] = [
  {
    name: "Branżowa Szkoła I Stopnia Nr 1 w Barlinku",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "sekretariat@zsipo.eu",
    type: [schoolTypes.SZKOLA_BRANZOWA],
  },
  {
    name: "I Liceum Ogólnokształcące w Barlinku",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "sekretariat@zsipo.eu",
    type: [schoolTypes.LICEUM],
  },
  {
    name: "Niepubliczna Szkoła Podstawowa RADOSNA",
    address: "ul. Szosowa 3",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "barlineckie.towarzystwo.edu@gmail.com",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Niepubliczne Przedszkole Językowe Wiśniowym Sadzie Jolanta Maria Rybarczyk",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "biuro@wwisniowymsadzie.pl",
    type: [schoolTypes.ODDZIAL_PRZEDSZKOLNY],
  },
  {
    name: "Klub Dziecięcy w Wiśniowym Sadzie Jolanta Maria Rybarczyk",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "biuro@wwisniowymsadzie.pl",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Niepubliczne Przedszkole Specjalne 'BRATEK'",
    address: "ul. Sienkiewicza 15",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "npbratek@gmail.com",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Przedszkole Miejskie nr 1 Janiny Porazińskiej",
    address: "ul. Kombatantów 3",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "przedszkole1.barlinek@poczta.fm",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Przedszkole Miejskie nr 2 'Pod Topolą' w Barlinku",
    address: "ul. Podwale 11",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "pm2@barlinek.stronyzklasa.pl",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Szkoła Podstawowa nr 1 im. Tadeusza Kościuszki w Barlinku",
    address: "ul. Jeziorna 12",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "sp1barli@interia.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Szkoła Podstawowa nr 4 im. Henryka Sienkiewicza w Barlinku",
    address: "ul. Kombatantów 3",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "sp4barlinek@gmail.com",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Szkoła Policealna dla dorosłych w Barlinku",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "sekretariat@zsipo.eu",
    type: [schoolTypes.SZKOLA_POLICEALNA],
  },
  {
    name: "Szkoła Przysposabiająca do Pracy",
    address: "ul. Sienkiewicza 15",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "spdbarlinek@gmail.com",
    type: [schoolTypes.SZKOLA_SPECJALNA], // dla osób z niepełnosprawnością
  },
  {
    name: "Technikum nr 1 w Barlinku",
    address: "ul. Szosowa 2",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "sekretariat@zsipo.eu",
    type: [schoolTypes.TECHNIKUM],
  },
  {
    name: "Żłobek miejski w Barlinek",
    address: "ul. Podwale 11",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "zlobekmiejski@onet.pl",
    type: [schoolTypes.ZLOBEK],
  },
  {
    name: "Ośrodek Szkolenia i Wychowania Ochotniczych Hufców Pracy w Barlinku",
    address: "ul. Św. Bonifacego 36",
    city: "Barlinek",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "osiw.barlinek@zachodniopomorska.ohp.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA, schoolTypes.SZKOLA_BRANZOWA],
  },
  {
    name: "Niepubliczna Szkoła Podstawowa w Barnówku",
    address: "Barnówko",
    city: "Barnówko",
    postalCode: "74-311",
    municipality: "Różańsko",
    email: "szkola.barnowko@yahoo.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Niepubliczne Małe Przedszkole w Barnówku",
    address: "Barnówko",
    city: "Barnówko",
    postalCode: "74-311",
    municipality: "Różańsko",
    email: "szkola.barnowko@yahoo.pl",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Przedszkole Gminne w Boleszkowicach",
    address: "ul. Słoneczna 24a",
    city: "Boleszkowice",
    postalCode: "74-407",
    municipality: "Boleszkowice",
    email: "gboleszkowice@wp.pl",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Szkoła Podstawowa im. Bolesława Chrobrego w Boleszkowicach",
    address: "Pl. Bolesława Chrobrego 3 oraz ul. Słoneczna 24 (IV-VIII)",
    city: "Boleszkowice",
    postalCode: "74-407",
    municipality: "Boleszkowice",
    email: "gboleszkowice@wp.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Punkt Przedszkolny 'Puchatek' w Cychrach",
    address: "ul. Jana Pawła II 66/5",
    city: "Cychry",
    postalCode: "74-404",
    municipality: "Cychry",
    email: "monika.rebiasz@interia.pl",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Szkoła Podstawowa im. Marii Konopnickiej w Sarbinowie",
    address: "Sarbinowo 80",
    city: "Sarbinowo",
    postalCode: "74-404",
    municipality: "Cychry",
    email: "szkolasarbinowo@wp.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Szkoła Podstawowa im. Władysława St. Reymonta w Cychrach",
    address: "ul. Jana Pawła II 85",
    city: "Cychry",
    postalCode: "74-404",
    municipality: "Cychry",
    email: "sekretariat@spcychry.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Niepubliczne Przedszkole Montessori z oddziałami integracyjnymi i specjalnymi Żaneta Rybińska-Prostak, Joanna Kujawa S.C.",
    address: "Dargomyśl 102",
    city: "Dargomyśl",
    postalCode: "74-404",
    municipality: "Dębno",
    email: "montessoridargomysl@gmail.com",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Branżowa Szkoła I Stopnia w Dębnie",
    address: "ul. Zachodnia 4",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "zsdebno@wp.pl",
    type: [schoolTypes.SZKOLA_BRANZOWA],
  },
  {
    name: "I Liceum Ogólnokształcące w Dębnie",
    address: "ul. Zachodnia 4",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "zsdebno@wp.pl",
    type: [schoolTypes.LICEUM],
  },
  {
    name: "Niepubliczna Szkoła Podstawowa w Dębnie",
    address: "ul. Baczewskiego 20",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Niepubliczne Liceum Ogólnokształcące",
    address: "ul. Baczewskiego 20",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "sto@stodebno.net",
    type: [schoolTypes.LICEUM],
  },
  {
    name: "Przedszkole Specjalnego Towarzystwa Salezjańskiego im. Św. Jana Bosko",
    address: "ul. Mickiewicza 33",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Niepubliczne Przedszkole Towarzystwa Salezjańskiego im. Św. Jana Bosko",
    address: "Plac Konstytucji 3 Maja 2",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "naszdom@onet.pl; naszdomdebno@gmail.pl",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Przedszkole nr 1 Czarodziejska Kraina w Dębnie",
    address: "ul. Kościuszki 6",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "czarodziejskakraina@buziaczek.pl",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Przedszkole nr 2 im. Stanisławy Modrzejewskiej w Dębnie",
    address: "ul. Jana Pawła II 42",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "p2debno@wp.pl",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Szkoła Podstawowa nr 1 im. KEN w Dębnie",
    address: "ul. Marszałka J. Piłsudskiego 10",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "sekretariat@sp1debno.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Szkoła Podstawowa nr 2 im. Arkadego Fiedlera w Dębnie",
    address: "ul. Jana Pawła II 1",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "sekretariat@sp2debno.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Szkoła Podstawowa nr 3 im. J. Dąbrowskiego",
    address: "ul. J. Słowackiego 21",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "sekretariat@sp3debno.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Szkoła Podstawowa Towarzystwa Salezjańskiego im. św. Jana Bosko w Dębnie",
    address: "ul. Mickiewicza 33",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "sekretariatsts@gmail.com",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Szkoła Policealna dla Dorosłych w Dębnie",
    address: "ul. Zachodnia",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "zsdebno@wp.pl",
    type: [schoolTypes.SZKOLA_POLICEALNA],
  },
  {
    name: "Żłobek Gminny w Dębnie",
    address: "ul. Jana Pawła II 42",
    city: "Dębno",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "p2debno@wp.pl",
    type: [schoolTypes.ZLOBEK],
  },
  {
    name: "Szkoła Podstawowa im. Adama Mickiewicza w Golenicach",
    address: "Golenice 1a",
    city: "Golenice",
    postalCode: "74-300",
    municipality: "Myslibórz",
    email: "szkolagolenice@wp.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Przedszkole Gminne w Karsku",
    address: "ul. Gorzowska 9",
    city: "Karsko",
    postalCode: "74-305",
    municipality: "Karsko",
    email: "sekretariat@zpokarsko.pl",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Szkoła Podstawowa im. H. Ch. Andersena w Karsku",
    address: "ul. Gorzowska 9",
    city: "Karsko",
    postalCode: "74-305",
    municipality: "Karsko",
    email: "sekretariat@zpokarsko.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Szkoła Podstawowa im. Janusza Korczaka w Kierzkowie",
    address: "Kierzków 69",
    city: "Kierzków",
    postalCode: "74-300",
    municipality: "Myślibórz",
    email: "szkolakierzkow@gmail.com",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Szkoła Podstawowa im. Jana Pawła II w Mostkowie",
    address: "74-322 Mostkowo 37D",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
    email: "sekretariat@mosmysliborz.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Niepubliczne Przedszkole im. Żwirka i Muchomorka",
    address: "ul. Armii Polskiej 13",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
    email: "p.zwirkaimuchomorka@gmail.com",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Oddział I Żłobka Miejskiego w Myśliborzu",
    address: "ul. Spokojna 22",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
    email: "pp2.mysliborz@o2.pl",
    type: [schoolTypes.ZLOBEK],
  },
  {
    name: "Przedszkole Publiczne Nr 1 'Zielona Dolinka' w Myśliborzu",
    address: "ul. Lipowa 18b",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
    email: "pp1.zielonadolinka@mysliborz.pl",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Przedszkole Publiczne nr 2 Misia Uszatka",
    address: "ul. Spokojna 12",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
    email: "pp2.mysliborz@o2.pl",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Specjalny Ośrodek Szkolno-Wychowawczy TPD w Myśliborzu",
    address: "ul. Pileckiego 27/Spokojna 22",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
    email: "soswtpd@soswtpd.pl",
    type: [schoolTypes.SPECJALNY_OSRODEK_SZKOLNO_WYCHOWAWCZY],
  },
  {
    name: "Szkoła Podstawowa nr 2 im. Janusza Kusocińskiego w Myśliborzu",
    address: "ul. Piłsudskiego 18",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
    email: "sekretariat@sp2mysliborz.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Szkoła Podstawowa nr 3 im. Leonida Teligi w Myśliborzu",
    address: "ul. Lipowa 18a",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
    email: "sp3mysliborz@wp.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA, schoolTypes.ODDZIAL_PRZEDSZKOLNY],
  },
  {
    name: "Szkoła Policealna w Myśliborzu",
    address: "ul. Strzelecka 51",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
    email: "sekretariat@zsipomysliborz.pl",
    type: [schoolTypes.SZKOLA_POLICEALNA],
  },
  {
    name: "Technikum nr 1 w Myśliborzu",
    address: "ul. Strzelecka 51",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
    email: "sekretariat@zsipomysliborz.pl",
    type: [schoolTypes.TECHNIKUM],
  },
  {
    name: "Technikum nr 2 Myśliborzu",
    address: "ul. Za Bramką 8",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
    email: "zsp2_mysliborz@poczta.onet.pl",
    type: [schoolTypes.TECHNIKUM],
  },
  {
    name: "Żłobek miejski w Myśliborzu",
    address: "ul. Spokojna 15",
    city: "Myślibórz",
    postalCode: "74-300",
    municipality: "Myślibórz",
    email: "pp2.mysliborz@o2.pl",
    type: [schoolTypes.ZLOBEK],
  },
  {
    name: "Szkoła Podstawowa im. Jana Brzechwy w Nawrocku",
    address: "Nawrocko 11",
    city: "Nawrocko",
    postalCode: "74-300",
    municipality: "Myślibórz",
    email: "sp.nawrocko@wp.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Szkoła Podstawowa im. Unii Europejskiej",
    address: "ul. Szkolna 4",
    city: "Nowogródek Pomorski",
    postalCode: "74-304",
    municipality: "Nowogródek Pomorski",
    email: "spnowogrodek@o2.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
  {
    name: "Szkoła Podstawowa im. Kornela Makuszyńskiego w Różańsku",
    address: "74-311 Różańsko 87",
    city: "Różańsko",
    postalCode: "74-311",
    municipality: "Różańsko",
    email: "sprozansko@sprozansko.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA, schoolTypes.ODDZIAL_PRZEDSZKOLNY],
  },
  {
    name: "Niepubliczne Przedszkole 'Małe Przedszkole' w Rychnowie",
    address: "Rychnów 57",
    city: "Rychnowo",
    postalCode: "74-320",
    municipality: "Barlinek",
    email: "aga_wita@interia.pl",
    type: [schoolTypes.PRZEDSZKOLE],
  },
  {
    name: "Młodzieżowy Ośrodek Socjoterapi w Smolnica",
    address: "Smolnica 51",
    city: "Smolnica",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "smolnica@smolnica.pl",
    type: [schoolTypes.MLODZIEZOWY_OSRODEK_SOCJOTERAPII],
  },
  {
    name: "Szkoła Podstawowa nr 1 im. Młodych Talentów w Smolnicy",
    address: "Smolnica 21",
    city: "Smolnica",
    postalCode: "74-400",
    municipality: "Dębno",
    email: "sp1smolnica@sp1smolnica.pl",
    type: [schoolTypes.SZKOLA_PODSTAWOWA],
  },
];
