import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import theme from "@/providers/ThemeProvider";
import { ThemeProvider } from "@mui/material";
import Navbar from "@/components/ui/top-navbar";
import { NavProvider } from "@/providers/NavProvider";
import SideDrawer from "@/components/ui/side-drawer";
import { UserProvider } from "@/providers/UserContext";
import { SearchProvider } from "@/providers/SearchProvider";
import LocalizationProviderClient from "@/providers/LocalizationProvder";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppRouterCacheProvider>
          <LocalizationProviderClient>
            <ThemeProvider theme={theme}>
              <SearchProvider>
                <UserProvider>
                  <NavProvider>
                    <Navbar />
                    <SideDrawer />
                    {children}
                  </NavProvider>
                </UserProvider>
              </SearchProvider>
            </ThemeProvider>
          </LocalizationProviderClient>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
